---
abstract: 'Secure Remote Protocol'
author:
  - 'Karel Miko'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.76, CPAN::Meta::Converter version 2.132510'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Crypt-SRP
no_index:
  directory:
    - t
    - inc
requires:
  Digest::SHA: 0
  MIME::Base64: 0
  Math::BigInt: 1.991
  Storable: 0
  Test::More: 0.88
  perl: 5.006
resources:
  repository: https://github.com/DCIT/perl-Crypt-SRP
version: 0.014
